export const reports = [
  {
    slug: "gate-in-out",
    title: "Gate In/Out",
    description: "Gate entry and exit activity report.",
    implemented: true,
  },
  {
    slug: "more-than-2-card",
    title: "More Than 2 Card",
    description: "Cards issued beyond the allowed limit.",
    implemented: true,
  },
  {
    slug: "card-expired-report",
    title: "Expired Card",
    description: "Expired card status and validity details.",
    implemented: true,
  },
  {
    slug: "card-issued",
    title: "Card Issued",
    description: "Issued card records and related pass details.",
    implemented: true,
  },
  {
    slug: "card-last-issued",
    title: "Card Last Issued",
    description: "Latest issued card entries.",
    implemented: true,
  },
  {
    slug: "revenue-report",
    title: "RevenueReport",
    description: "Revenue details generated from passes.",
    implemented: true,
  },
  {
    slug: "wharfage-report",
    title: "WharfageReport",
    description: "Wharfage-related operational summary.",
    implemented: true,
  },
  {
    slug: "card-penalty-report",
    title: "CardPenaltyReport",
    description: "Penalty records associated with cards.",
    implemented: true,
  },
  {
    slug: "card-lost-report",
    title: "CardLostReport",
    description: "Lost card report and recovery status.",
    implemented: true,
  },
  {
    slug: "individual-card-query-report",
    title: "IndividualCardQuery Report",
    description: "Individual person or vehicle card lookup report.",
    implemented: true,
  },
  {
    slug: "total-passid-report",
    title: "TotalPassid Report",
    description: "Total pass ID summary report.",
    implemented: false,
  },
  {
    slug: "manual-pass-report",
    title: "ManualPass Report",
    description: "Manual pass issuance details.",
    implemented: false,
  },
  {
    slug: "cargo-report",
    title: "Cargo Report",
    description: "Cargo movement and material pass details.",
    implemented: false,
  },
  {
    slug: "pass-approval-report",
    title: "Pass Approval Report",
    description: "Approval status tracking across pass requests.",
    implemented: false,
  },
  {
    slug: "registered-users",
    title: "Registered Users",
    description: "Company and user account information.",
    implemented: true,
  },
  {
    slug: "type-of-pass-issued",
    title: "Type of Pass Issued",
    description: "Pass issuance grouped by pass type.",
    implemented: true,
  },
  {
    slug: "cargo-summary-report",
    title: "Cargo Summary Report",
    description: "Summary-level view of cargo pass activity.",
    implemented: false,
  },
  {
    slug: "pre-own-card-status-report",
    title: "Pre Own Card Status Report",
    description: "Pre-owned card status and availability.",
    implemented: false,
  },
  {
    slug: "card-inventory-report",
    title: "CardInventory Report",
    description: "Detailed inventory status of cards.",
    implemented: true,
  },
  {
    slug: "intercarting-vehicle-report",
    title: "Intercarting Vehicle Report",
    description: "Intercarting vehicle movement and usage details.",
    implemented: false,
  },
  {
    slug: "intercarting-machinary-report",
    title: "Intercarting Machinary Report",
    description: "Intercarting machinery movement and usage details.",
    implemented: false,
  },
  {
    slug: "cargo-out-report",
    title: "Cargo Out Report",
    description: "Outgoing cargo and material movement details.",
    implemented: false,
  },
  {
    slug: "gate-wise-in-out-summary",
    title: "Gate Wise In/Out Summary",
    description: "Gate-wise summary of in and out movements.",
    implemented: false,
  },
  {
    slug: "gate-lane-wise-in-out-summary",
    title: "Gate Lane Wise In/Out Summary",
    description: "Lane-wise summary of in and out movements.",
    implemented: false,
  },
  {
    slug: "revenue-report-summary",
    title: "Revenue Report Summary",
    description: "Summary report for revenue generated from passes.",
    implemented: false,
  },
  {
    slug: "card-inventory-summary",
    title: "Card Inventory summary",
    description: "Summary-level card inventory report.",
    implemented: true,
  },
  {
    slug: "transaction-report-in-out",
    title: "Transaction Report(In & Out)",
    description: "Inward and outward transaction activity report.",
    implemented: false,
  },
  {
    slug: "transaction-register",
    title: "Transaction Register",
    description: "Register of operational transactions.",
    implemented: false,
  },
  {
    slug: "all-pass-issuance-report",
    title: "ALL PASS ISSUANCE REPORT",
    description: "Combined issuance report for all pass types.",
    implemented: true,
  },
];

export const getReport = (slug) =>
  reports.find((report) => report.slug === slug);
