import "./globals.css";
import { Toaster } from "sonner";

export const metadata = {
  title: "Chennai Port Gate Automation System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
      style={{ fontFamily: 'Arial, sans-serif' }}
    >
      <body 
        className="min-h-full flex flex-col" 
        style={{ fontFamily: 'Arial, sans-serif' }}
        suppressHydrationWarning
      >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
