import "./globals.css";
import { Toaster } from "sonner";
import ChatbotWidget from "../components/ChatbotWidget";

export const metadata = {
  title: "Automated Port Access and Control System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning
      >
        {children}
        <ChatbotWidget />
        <Toaster position="top-center" richColors />
      </body>
    </html>
  );
}
